# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 863)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: rgb(226, 209, 137) ;\n"
"    color: rgb(171, 111, 61)  ;\n"
"    font-family: Arial;\n"
"    \n"
"}    \n"
"\n"
"")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 100, 1511, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(0, 116, 0);\n"
"   \n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 740, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(171, 111, 61)  ;\n"
"    font-family: Arial;\n"
"     border: 3px solid #5C3317;\n"
"    border-radius: 10px; \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 740, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: rgb(171, 111, 61)  ;\n"
"    font-family: Arial;\n"
"     border: 3px solid #5C3317;\n"
"    border-radius: 10px; \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 740, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: rgb(171, 111, 61)  ;\n"
"    font-family: Arial;\n"
"     border: 3px solid #5C3317;\n"
"    border-radius: 10px; \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 740, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: rgb(171, 111, 61)  ;\n"
"    font-family: Arial;\n"
"     border: 3px solid #5C3317;\n"
"    border-radius: 10px; \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tableWidget, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Patients Portal"))
        self.pushButton.setText(_translate("Dialog", "Add"))
        self.pushButton_3.setText(_translate("Dialog", "Delate"))
        self.pushButton_2.setText(_translate("Dialog", "Statistic"))
        self.pushButton_4.setText(_translate("Dialog", "Update"))
