# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 863)
        Dialog.setMinimumSize(QtCore.QSize(100, 100))
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: rgb(226, 209, 137) ;\n"
"}\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(360, 230, 1121, 161))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(66)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(0, 116, 0);\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(680, 460, 281, 81))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(171, 111, 61)  ;\n"
"    font-family: Arial;\n"
"    font-size: 30pt;\n"
"     border: 3px solid #5C3317;\n"
"    border-radius: 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Psychologist\'s Portal"))
        self.pushButton.setText(_translate("Dialog", "open"))
